# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs/Home.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 445)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designs\\../icons/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(200, 340))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scrollArea_2.setBaseSize(QtCore.QSize(200, 0))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 210, 386))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bhome = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.bhome.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bhome.setToolTip("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Designs\\../icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bhome.setIcon(icon1)
        self.bhome.setObjectName("bhome")
        self.verticalLayout_3.addWidget(self.bhome)
        self.addwid = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.addwid.setMaximumSize(QtCore.QSize(1000, 20))
        self.addwid.setToolTipDuration(-100)
        self.addwid.setAlignment(QtCore.Qt.AlignCenter)
        self.addwid.setObjectName("addwid")
        self.verticalLayout_3.addWidget(self.addwid)
        self.scrollArea = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 192, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.bdel = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.bdel.setMaximumSize(QtCore.QSize(16777215, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Designs\\../icons/Edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bdel.setIcon(icon2)
        self.bdel.setObjectName("bdel")
        self.verticalLayout_3.addWidget(self.bdel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.frame = QtWidgets.QTabWidget(self.splitter)
        self.frame.setMinimumSize(QtCore.QSize(470, 0))
        self.frame.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.frame.setObjectName("frame")
        self.framePage1 = QtWidgets.QWidget()
        self.framePage1.setObjectName("framePage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.framePage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.framePage1)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame.addTab(self.framePage1, "")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.addwid, self.bhome)
        MainWindow.setTabOrder(self.bhome, self.bdel)
        MainWindow.setTabOrder(self.bdel, self.frame)
        MainWindow.setTabOrder(self.frame, self.scrollArea_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WorkHours"))
        self.bhome.setStatusTip(_translate("MainWindow", "Home Window"))
        self.bhome.setText(_translate("MainWindow", " HOME"))
        self.addwid.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press <span style=\" color:#ff0000;\">Enter</span> to Add</p></body></html>"))
        self.addwid.setStatusTip(_translate("MainWindow", "Press Enter to Add New Widget"))
        self.addwid.setPlaceholderText(_translate("MainWindow", "Add New Widget"))
        self.bdel.setStatusTip(_translate("MainWindow", "Comming Soon"))
        self.bdel.setText(_translate("MainWindow", "Smart Widget"))
        self.label.setText(_translate("MainWindow", "WorkHours"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
